Algoritmo "impares"
// Disciplina   : [Lógica de Programação]
// Professor   : Thalia Souza
// Autor(a)    : Juan da Silva Gomes
// Data atual  : 08/04/2025
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 20 faca
        se nao(i % 2 = 0) entao
           escreval(i)
        fimse
   fimpara

Fimalgoritmo