Algoritmo "senha"
// Disciplina   : [Lógica de Programação]
// Professor   : Thalia Souza
// Autor(a)    : Juan da Silva Gomes
// Data atual  : 13/03/2025
Var
// Seção de Declarações das variáveis 
   senha: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Insira a senha: ")
   leia(senha)
   
   se (senha = "1234") entao
      escreval("Acesso permitido!")
   senao
      escreval("Acesso negado!")
   fimse

Fimalgoritmo