Algoritmo "notas-para"
// Disciplina   : [Lógica de Programação]
// Professor   : Thalia Souza
// Autor(a)    : Juan da Silva Gomes
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 
   i: inteiro
   nota: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i de 1 ate 7 faca
        escreval("Insira a nota do ", i, " aluno:")
        leia(nota)
        escreval("Nota do ", i, "° aluno:", nota)
   fimpara

Fimalgoritmo